### ISSUE TITLE
How to add local packages into maven repository?

### ISSUE THREAD

**Issue by datakurre** [fzakaria/mvn2nix#15]
When building maven repository manually as described in https://fzakaria.com/2020/07/20/packaging-a-maven-application-with-nix.html, it is possible to add local jar packages into mix with `mvn install:install-file` without having them in any repositories.

Is this already possible somehow with mvn2nix or would be hard to add? Obviously those other packages could also be packaged with the help of mv2nix, but not sure if that makes any difference :thinking:

**Comment by fzakaria** [comment]
`mvn2nix` might fail since it expects all jar packages to be present in _any remote repository_
(Maybe there's a case here to make that a graceful failure)

If you have local JARs, the solution I can see is:
1. run mvn2nix to generate dependencies.nix
2. the actual _default.nix_ derivation would need to augment buildMavenRepository to include the local JARs

**Comment by datakurre** [comment]
@fzakaria Thanks. I had not checked how simple `buildMavenRepository` reallly was. Augmenting / customizing that could be my solution. It should even allow passing other mvn2nix built "local JARs" as derivations for linkFarm to allow compose maven projects without remote repository.

**Comment by datakurre** [comment]
@fzakaria I forgot to mention that the current master seemed to work for the projects I was working on. Thank you!

**Comment by fzakaria** [comment]
Thanks @datakurre glad it worked!
Please consider contributing to augment `buildMavenRepository` with ideas to support local jars or at least document in the README :)
